# Generated by Django 4.2.7 on 2023-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('vendor_code', models.CharField(max_length=50)),
            ],
        ),
    ]
