# Generated by Django 4.2.7 on 2023-11-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchage_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchage_order',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
