# Generated by Django 4.2.7 on 2023-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchage_order', '0002_alter_purchage_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchage_order',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
